name: autonity
apiVersion: v1
version: 1.2.1
kubeVersion: ">=1.15.11-0"
description: Deploy single Autonity instance
keywords:
- autonity
- blockchain
home: https://www.autonity.io/
sources:
- https://github.com/clearmatics/autonity
maintainers:
- name: eastata
  email: aleksandr.poliakov@clearmatics.com
appVersion: v0.4.1
