name: autonity-network
apiVersion: v1
version: 1.8.1
kubeVersion: ">=1.15.11-0"
description: Chart for deploying a full Autonity network
keywords:
- autonity
- blockchain
home: https://www.autonity.io/
sources:
- https://github.com/clearmatics/autonity
maintainers:
- name:  eastata
  email: aleksandr.poliakov@clearmatics.com
appVersion: v0.6.0
