---
apiVersion: v1
kind: ConfigMap
metadata:
  name: genesis
  namespace: {{ .Release.Namespace }}
data: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: genesis-template
  namespace: {{ .Release.Namespace }}
data:
  genesis:  |-
{{ if .Values.genesis }} {{ toJson .Values.genesis | indent 4 }}
{{else}} {{ toJson .Values.default_genesis | indent 4 }}
{{end}}