{{- if or (eq .Values.aws_persistent_storage_enabled true) (eq .Values.gcp_persistent_storage_enabled true) }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: blockchain-{{ .Release.Name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
{{ if eq .Values.aws_persistent_storage_enabled true }}
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
  encrypted: "true"
{{ else if  eq .Values.gcp_persistent_storage_enabled true}}
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
{{ end }}
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-autonity-node-0-blockchain
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: blockchain-{{ .Release.Name }}
  resources:
    requests:
      storage: {{ .Values.blockchain_persistent_volume_size }}

{{- end}}
