name: "Integration Tests and Publish on Tag"

on:
  push:
    tags:
    - 'autonity-v[0-9]+.[0-9]+.[0-9]+*'
    - 'audonity-demo-v[0-9]+.[0-9]+.[0-9]+*'
    - 'autonity-network-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  integration_tests_publish_on_tag:
    runs-on: ubuntu-20.04

    steps:
    - name: git checkout
      uses: actions/checkout@v2
      with:
        repository: clearmatics/charts-ose-helm3
        ref: helm2to3start

    - name: Set useful variables
      run: |
        echo '::set-env name=CHART_PATH::stable/'$(echo ${GITHUB_REF##*/} | awk -F '-' '{print $1}')
        echo '::set-env name=SHORT_SHA::'$(echo $GITHUB_SHA|head -c 7)
        echo '::set-env name=S3_BUCKET_NAME::charts-ose.clearmatics.com'

    - name: Get useful variables
      run: |
        echo 'Chart path: '$CHART_PATH
        echo 'Actor: '$GITHUB_ACTOR
        echo 'Short SHA: '$SHORT_SHA

    - name: Setup gcloud environment
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.2
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure the kubeconfig
      run: gcloud container clusters get-credentials tf-gke-helm --zone ${{ secrets.GCP_PROJECT_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Install helm
      uses: azure/setup-helm@v1
      with:
        version: '3.2.4'
      id: install

    - name: Deploy the chart
      run: |
        helm install $GITHUB_HEAD_REF-$SHORT_SHA $CHART_PATH --namespace $GITHUB_ACTOR
        # Sadly --wait fails, so have to sleep, look to maybe pull in mock test to solve
        # this problem another way
        sleep 60
    - name: Run the tests
      run: helm test $GITHUB_HEAD_REF-$SHORT_SHA

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Sync repo locally
      run: |
        mkdir -p repo
        aws s3 sync s3://${S3_BUCKET_NAME} repo

    - name: Package the chart
      run: |
        helm package ${CHART_PATH} -d "repo" --save=false --debug
        helm repo index ./repo

    - name: Publish the chart
      run: |
        aws s3 cp ./repo/${GITHUB_REF##*/}.tgz s3://${S3_BUCKET_NAME}

    - name: Publish the main index
      run: |
        aws s3 cp ./repo/index.yaml s3://${S3_BUCKET_NAME} --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type "text/plain"
    - name: Cleanup
      run: helm delete $GITHUB_HEAD_REF-$SHORT_SHA
